spring:
  application:
    name: stockhub-backend

  datasource:
    url: ${STOCKHUB_JDBC_URL:jdbc:postgresql://localhost:5432/stockhub}
    username: ${STOCKHUB_DB_USER:stockhub_user}
    password: ${STOCKHUB_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

doma:
  dialect: postgres

server:
  port: 8080
